# Generated by Django 4.2.11 on 2024-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('Su', 'Succeess'), ('S', 'secondary'), ('D', 'danger')], default='Su', max_length=20),
        ),
    ]
